# Generated by Django 3.1.2 on 2021-04-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210427_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tweets',
            new_name='tweeter',
        ),
    ]
