# Generated by Django 3.1.2 on 2021-04-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210427_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tweeter',
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, help_text='Provide link to your Twitter account (optional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, help_text='Provide link to your Facebook account (optional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='google_plus',
            field=models.CharField(blank=True, help_text='Provide link to your Google Plus account (optional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Provide link to your instagram account (optional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linked_in',
            field=models.CharField(blank=True, help_text='Provide link to your Linked In account (optional)', max_length=200, null=True),
        ),
    ]
