# Generated by Django 3.1.2 on 2021-04-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210427_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='works_at',
            field=models.CharField(blank=True, help_text='Tell us where you currently work (optional)', max_length=200, null=True),
        ),
    ]
