# Generated by Django 3.1.2 on 2021-04-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_works_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_policy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
