# Generated by Django 3.1.2 on 2021-04-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_has_seen_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic/profile.png', upload_to='profile_pics/'),
        ),
    ]
