# Generated by Django 3.1.2 on 2021-05-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210430_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_company',
            field=models.BooleanField(default=False),
        ),
    ]
