# Generated by Django 3.1.2 on 2021-05-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210501_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriped',
            field=models.BooleanField(default=False),
        ),
    ]
