# Generated by Django 3.1.2 on 2021-04-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='null', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
