# Generated by Django 3.1.2 on 2021-04-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_auto_20210423_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
