# Generated by Django 3.1.2 on 2021-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_auto_20210423_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_applicants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
