# Generated by Django 3.1.2 on 2021-04-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0008_auto_20210426_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selected',
            old_name='jobs',
            new_name='job',
        ),
    ]
