# Generated by Django 3.1.2 on 2021-04-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0009_auto_20210426_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Remote', 'Remote'), ('Contract', 'Contract')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, help_text='Provide a link to your site if only you wish the applicants to apply on your site', max_length=1024, null=True),
        ),
    ]
