# Generated by Django 3.1.2 on 2021-05-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0012_auto_20210426_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, default='job_pics/job.jpeg', null=True, upload_to='job_pics/'),
        ),
    ]
