# Generated by Django 3.1.2 on 2021-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0013_auto_20210501_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, default='job.jpeg', null=True, upload_to='job_pics/'),
        ),
    ]
