# Generated by Django 3.1.2 on 2021-05-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0014_auto_20210501_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='job.jpeg', upload_to='job_pics/'),
        ),
    ]
