# Generated by Django 3.1.2 on 2021-05-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0016_job_applied_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='selected_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
