# Generated by Django 3.1.2 on 2021-05-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0017_job_selected_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='selected_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
