# Generated by Django 3.1.2 on 2021-05-10 22:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0019_auto_20210503_1143'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('activejobs', django.db.models.manager.Manager()),
            ],
        ),
    ]
