# Generated by Django 3.1.2 on 2021-05-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0020_auto_20210510_2315'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
            ],
        ),
    ]
