# Generated by Django 3.1.2 on 2021-05-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0022_auto_20210526_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
    ]
