# Generated by Django 3.1.2 on 2021-05-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0023_auto_20210526_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
