# Generated by Django 3.1.2 on 2021-05-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0026_auto_20210529_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='intro',
            field=models.TextField(help_text='Enter a brief description of the job post', null=True),
        ),
    ]
