# Generated by Django 3.1.2 on 2021-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210426_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lind_of_engagement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
