# Generated by Django 3.1.2 on 2021-05-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_lind_of_engagement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='lind_of_engagement',
            new_name='line_of_engagement',
        ),
    ]
