# Generated by Django 3.1.2 on 2021-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20210503_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
