# Generated by Django 3.1.2 on 2021-05-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
