# Generated by Django 3.1.2 on 2021-05-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, help_text='Your facebook page link, Optional', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='google',
            field=models.CharField(blank=True, help_text='Your google plus page link, Optional', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, help_text='Your facebook page link, Optional', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Your linkedin page link, Optional', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, help_text='Your twitter page link, Optional', max_length=255, null=True),
        ),
    ]
