# Generated by Django 3.1.2 on 2021-05-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20210503_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='none.png', null=True, upload_to='companies'),
        ),
    ]
